name: donovanpreddy
favicon: null
layout_spectrum: 0.716208016499877
typography_spectrum: 0.2391899882350117
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7635890992823988
  lightness: 0.969913829350844
  saturation: 0.37226139241829515
  rhythmicContrast: 0.4571480294689536
purpose: []
